### ISSUE TITLE
关于上传蒲公英

### ISSUE THREAD

**Issue by q32784307** [90candy/AutoPackage#1]
您好，请问如果上传到蒲公英的话，更新信息的文案在脚本的哪里填写呢

**Comment by AAWayne** [comment]
抱歉，才看到，这个由于是之前写的，用的蒲公英 1.0 API 的，后面我更新 2.0 API 就直接把这个也给加上：
加一个更新文案字段去配置即可：update_description

`curl -F "file=@${ipa_path}" -F "uKey=${ukey}" -F "_api_key=${api_key}" -F "installType=${pgy_installType}" -F "password=${pgy_password}" -F "updateDescription=${update_description}" https://qiniu-storage.pgyer.com/apiv1/app/upload`

**Comment by q32784307** [comment]
感谢大佬的回复，这个问题我通过查看蒲公英的api已经解决了。现在有另外一个问题，不知道怎么回事儿，打包会Archive操作失败，这个我也没看出具体报错是因为什么。肯定是先手动打过包的

**Comment by q32784307** [comment]
会不会跟M1芯片有关系？

**Comment by q32784307** [comment]
已解决
